services:
  nodejsavilcatoma:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=8000
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGHOST=db
      - PGPORT=$PGPORT
      - PGDATABASE=$PGDATABASE
    ports:
      - "8000:8000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:5432 -- /home/node/app/node_modules/.bin/nodemon bin/www

  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_DB=$PGDATABASE
    volumes:     
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: